#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-stabs
Version  : 0.6.3
Release  : 1
URL      : https://cran.r-project.org/src/contrib/stabs_0.6-3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/stabs_0.6-3.tar.gz
Summary  : Stability Selection with Error Control
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : R-QUIC
BuildRequires : buildreq-R

%description
stabs
=====
[![Build Status](https://travis-ci.org/hofnerb/stabs.svg)](https://travis-ci.org/hofnerb/stabs)
[![Build status](https://ci.appveyor.com/api/projects/status/tlo7dbrevje1f2du?svg=true)](https://ci.appveyor.com/project/hofnerb/stabs)
[![Coverage Status](https://coveralls.io/repos/hofnerb/stabs/badge.svg?branch=master&service=github)](https://coveralls.io/github/hofnerb/stabs?branch=master)
[![CRAN Status Badge](http://www.r-pkg.org/badges/version/stabs)](https://cran.r-project.org/package=stabs)
[![](http://cranlogs.r-pkg.org/badges/stabs)](https://cran.r-project.org/package=stabs)

%prep
%setup -q -c -n stabs

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1584125741

%install
export SOURCE_DATE_EPOCH=1584125741
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library stabs
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library stabs
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library stabs
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc stabs || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/stabs/CITATION
/usr/lib64/R/library/stabs/DESCRIPTION
/usr/lib64/R/library/stabs/INDEX
/usr/lib64/R/library/stabs/Meta/Rd.rds
/usr/lib64/R/library/stabs/Meta/features.rds
/usr/lib64/R/library/stabs/Meta/hsearch.rds
/usr/lib64/R/library/stabs/Meta/links.rds
/usr/lib64/R/library/stabs/Meta/nsInfo.rds
/usr/lib64/R/library/stabs/Meta/package.rds
/usr/lib64/R/library/stabs/Meta/vignette.rds
/usr/lib64/R/library/stabs/NAMESPACE
/usr/lib64/R/library/stabs/NEWS.Rd
/usr/lib64/R/library/stabs/R/stabs
/usr/lib64/R/library/stabs/R/stabs.rdb
/usr/lib64/R/library/stabs/R/stabs.rdx
/usr/lib64/R/library/stabs/doc/Using_stabs.R
/usr/lib64/R/library/stabs/doc/Using_stabs.Rmd
/usr/lib64/R/library/stabs/doc/Using_stabs.html
/usr/lib64/R/library/stabs/doc/index.html
/usr/lib64/R/library/stabs/doc/stabs_graphs.R
/usr/lib64/R/library/stabs/doc/stabs_graphs.Rmd
/usr/lib64/R/library/stabs/doc/stabs_graphs.html
/usr/lib64/R/library/stabs/help/AnIndex
/usr/lib64/R/library/stabs/help/aliases.rds
/usr/lib64/R/library/stabs/help/paths.rds
/usr/lib64/R/library/stabs/help/stabs.rdb
/usr/lib64/R/library/stabs/help/stabs.rdx
/usr/lib64/R/library/stabs/html/00Index.html
/usr/lib64/R/library/stabs/html/R.css
